version: '3.3'
services:
  api:
    image: occupation_measurement/api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
  app:
    image: occupation_measurement/app
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    ports:
      - "3838:3838"
